sudo: required
privileged: true
language: node_js
cache: npm

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.6.2

node_js:
    '10.15.1'

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

  - docker-compose up --build -d
  - docker ps -a
  - docker exec -ti nodeapi npm install

