sudo: required
language: node_js
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.6.2
node_js:
    '10.15.1'
install:
    npm install
before_script:
    - npm run lint
script:
    - npm run build
    - npm test
