language: node_js

services:
  - docker

before_install:
  - docker-compose up --build

node_js:
    '10.15.1'
install:
    npm install
before_script:
    npm run lint
script:
    npm run build
    npm test
