language: node_js
sudo: required
services:
- docker
addons:
  code_climate:
    repo_token:
      secure: Ev1NOTJ4EasKjx6YxZX0XxdzRYEpXB65vwGwe4/kZ/oYifMDF1Ap8o6cwdlApvwwYYAv5wx6unyRjLYoBC/5R/Ad/DJNa+zlLNKNjCeQYMYneTcyxMg43YzbQl/1S0/NnSGwu6QObqG+mrdXtdVu2Ut0PIjt7rHCZO51No8DZPjuixGQDpTN5rSi0C7B+iNmsop15QpCCM760f/Nuy1zF5n+PvFTJsjqJpR6XzT7mbYeyecVcFfSVREYJJqrAfHCDl66m/1SNcf0Zj4av05+xUqGje4b1Rpu3gu/QyaDx6Z6+DwK1Ak0E85dadHuAaf8MUP7cMrPlAisrY53Cvlbi35LJvp/kvNObPXSqezC6AF5xOXhdEiArDeHekQv+/OpnpOOQjbJQ8dTVehz4p8ppKv2tm5pN+2A1W7EypH3QXSMDhU21ZMkKn52v6sr9olV8zL8CjTmDpHNvt4OH+CJ3caN5EJp9GyoDRK7/GDYquRB2IiNd5Oj0zp+nP7GfXYDDgqYFabkVQtxA0AsVB+UFAoRNsrGL+vNvqNTPx9z2ZXhWLfpYv8lWyuhuXxRRaAb3ZFy4B5EPc8b3XedYDV+Wp9YWSVOLsp8GTTLsk9ckkPGFvg5DsJcXE7UverVfJ4CB+yPsw635dxrG1VqJ8xVkXgE0K32frw/f6ake8qRYvw=
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - bernardo.amaral85@gmail.com
    on_failure: always
env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  NODE_ENV: development
  global:
    secure: qBKG7vu96XW5e9yWTsy29wkEjjDKXK8etjrGCdQS7qiV8m9KinkmHd5kIjrMMrLCjAyyIiOV9oMuHgD6Rik7thIDIoHDrg8K+y98X0QFzAJGdnuek6Zex15kIf9tDzOuhbd71h1tYJ1eBTHb/x4OV+absHXxhe0dYpgfj1/pbP8wLjabBEtHa667jY+PQ1hvfn+Vg0zxQhJXwJLv38RDqhatqGkvHcWyNRecXGrf72aXZ1mDN1tLEQ05+66rDaDDNtTOQPyqfHKTMeItxp6Mh47gtJ7PQxCYjSgmeIFq7OCaDAGuf3aJ3GOwX8Ru+AUlpYYr06INhghCF5w2gAR6Hb8VW4DOZdfN8YYy6Prxk8hUr5UoNvFLUy2AzAPI1c787EHXeOn+iWlmP+Npw8VsH0mOLbWYt/3DU6361udY7Qj9PYh55Vq0W9jwEkAq3w+f2zxLI0y41TFmLS552if6wl1prVqU77ZXKKvNKEZkrheDeHqw9CK//zM+YbvpAxtfXs4LKxcQRuBRSnzT3XKjZXqOmCEoH58BjvdcvhxqH/0IvikrGcQBpUU90WY8ZBQNDWItrLLPfnVQM1+dhCd+lEhq4Eh7jFf85xG7OAcKlAeSjWLNy1NDT/JdQJ79EsJC0t+sFzJtki55gexBvWmRkCHThcduB6hMT5fARAhunBw=
node_js: 10.15.1
before_install:
- npm install -g node-gyp
before_script:
- npm install
- npm install -g standard
- docker-compose build
- docker-compose up -d
- sleep 3
script:
- docker exec -it nodeapi bash -c "npm run migrate"
- docker exec -it nodeapi bash -c "npm run seed"
- docker exec -it nodeapi bash -c "npm test"
after_script:
- docker-compose kill
before_deploy: echo 'Deploying to Heroku...'
deploy:
  provider: heroku
  api_key:
    secure: e1Y4j80yoqIZ2EHVcDFnvcRnGmmYyrrYUcFrbWFaTFibg7t+7EqtUSQAyIKorqJf05OwnP3nighfdIfiaSxDo3ZkmdKpmnwM9WGmz914idGWqaDqfuIaMztky3+KK97ePatkgjItYLQ76SvWvfjdM8cd6LKXGsnuzbZrV6nf4eA4OHcLLOobFc/R+Or/qjXO/BaxedvAjl/dOI8Mm2t0+a87hX8eLvD8lfEfV4M+7cjiufYrPArKMFpc8lqoHGkefOgg2lMHy1G+rInx+y4fgSW0NGJlsLeF8wWAWQLDF9ZUjvOHBy0LgVYyqfhyghmMsb9uVZc35GrpY+TKBK/GIHrrwXsQLtk3UAt4Sly8WtMgqC11gc745QZdJDWJX1Ly+oa50gFLRrGCbxhT+yaRg/r08e3r2KaIMVHBLQ8ltJTNQzIbjUpXg84EwP5GKY7b8z+kCbmy2wEEH/JeKn+QYYMFraSqjiiWxvscs8SGpmBU7j+jqO9JqwVPGkRSudmPWvIREByVvvVJHIfX3Pv5bjp1h6LQYQ+PXZNxeemRFk1H1jKp2GTx+Mnf5CR6SyPrMvkVL09wPuZuDA1tMMEdb/y407swR2wm9Ma/l0GkjUF9hy2apzYYy9CfycKduWqS2nP/z2THPV3FOFEFgMjaIJK4JkfNUqindHp529UB8bU=
  app: games-node-api
  skip_cleanup: false
after_deploy: echo 'Heroku done!'
