privileged: true
language: node_js
cache: npm

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

node_js:
    '10.15.1'

before_install:
  - docker-compose --version
  - docker-compose build
  - docker-compose up -d
  - docker stats --no-stream
  - docker exec -it nodeapi bash -c "npm install"

script:
  - docker exec -it nodeapi bash -c "npm test"

