language: node_js
sudo: required

services:
  - docker

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - bernardo.amaral85@gmail.com
    on_failure: always

env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  NODE_ENV: test

node_js:
    '10.15.1'

before_install:
  - npm install -g node-gyp
before_script:
  - npm install
  - npm install -g standard
  - docker-compose build
  - docker-compose up -d
  - sleep 3
script:
  - docker exec -it nodeapi bash -c "npm run migrate"
  - docker exec -it nodeapi bash -c "npm run seed"
  - docker exec -it nodeapi bash -c "npm test"
after_script:
  - docker-compose kill

before_deploy: "echo 'Deploying to Heroku...'"

deploy:
  provider: heroku
  api_key:
    secure: e3fc1ce6-2525-4ebc-8b24-ff33488a1067
  app: games-node-api
  skip_cleanup: false

after_deploy: "echo 'Heroku done!'"
