sudo: required
privileged: true
language: node_js
cache: npm

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

node_js:
    '10.15.1'

before_install:
  - sudo apt-get update
  - docker-compose up --build -d
  - docker ps -a
  - docker exec -ti nodeapi bash
  - npm install
  - npm test

script:
  - docker ps -a
  - docker exec -it nodeapi bash
  - npm install

