sudo: required
privileged: true
language: node_js
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.6.2
node_js:
    '10.15.1'
before_install:
  - sudo apt-get update
install:
    sudo docker-compose build
    npm install
before_script:
    - npm run lint
script: 
    - sudo docker-compose up -d
    - npm run build
    - npm test
