version: '3.2'

services:
   nodejs:
    container_name: nodeapi
    build:
      context: ./.docker/node
      # args:
      #   - PROXY=10.203.222.109:3128
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - postgresql

   postgresql:
    container_name: apidb
    build: ./.docker/pg
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=apiadmin
      - POSTGRES_PASSWORD=apipass
      - POSTGRES_DB=myapi
      - PG_TRUST_LOCALNET=true
