version: '3.2'

services:
   postgresql:
    container_name: apidb
    build: ./.docker/pg
    ports:
      - "5432:5432"
      - "5435:5435"
    environment:
      - POSTGRES_USER=apiadmin
      - POSTGRES_PASSWORD=apipass
      - POSTGRES_DB=myapi
      - POSTGRES_PORT=5435
      - PG_TRUST_LOCALNET=true
