version: '3.2'

services:
  nodejs:
    container_name: docker-nodejs
    image: "node:latest"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    expose:
      - "80"
    command: "npm start"
    restart: always
    links:
      - mysql

  mysql:
    container_name: docker-mysql
    image: "mysql/mysql-server:latest"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password      
    environment:       
      - MYSQL_USER = dbuser
      - MYSQL_PASSWORD = dbpass
      - MYSQL_ROOT_PASSWORD = root
      - MYSQL_DATABASE = locadora
      - MYSQL_ROOT_HOST = %
      - MYSQL_HOST = %
      - MYSQL_ALLOW_EMPTY_PASSWORD = true      