version: '3.2'

services:
  mysql:
    container_name: docker-database
    build: ./.docker/db
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=apiadmin
      - MYSQL_PASSWORD=apipass
      - MYSQL_DATABASE=myapi
