version: '3.2'

services:
   postgresql:
    container_name: apidb
    build: ./.docker/pg
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=apiadmin
      - POSTGRES_PASSWORD=apipass
      - POSTGRES_DB=myapi
      - PG_TRUST_LOCALNET=true
