version: '3.2'

services:
  db:
    container_name: api-db
    build: ./.docker/db
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./docker/db/database.sql:/docker-entrypoint-initdb.d/dump.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=apiadmin
      - MYSQL_PASSWORD=apipass
      - MYSQL_DATABASE=myapi
